-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID,
COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
	SELECT 
		CAR_ID
	FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
	WHERE DATE_FORMAT(START_DATE,'%Y-%m') BETWEEN '2022-08' AND '2022-10'
	GROUP BY CAR_ID
	HAVING COUNT(CAR_ID) >= 5) -- 대여 횟수가 5회 이상인 데이터는 서브쿼리로 처리
AND (DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10') -- 위 기간 내 월별 CAR_ID 대여 횟수 조건
GROUP BY MONTH, CAR_ID -- 월별, CAR_ID 별 그룹화
HAVING COUNT(*) > 0 -- 대여 횟수가 0인 경우 제외
ORDER BY MONTH, CAR_ID DESC